Art_School_Products_Marketplace/Art_School_Products_Marketplace/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('register/', include('registr.urls')),
    path('about/', include('about.urls')),
    path('login/', include('login.urls')),
    path('products/', include('products.urls')),
    path('products_detail/', include('products_detail.urls')),
    path('product_cards/', include('productCard.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rules/', include('rules.urls')),
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Art_School_Products_Marketplace/about/urls.py
from django.urls import path
from .views import about_page


app_name = 'about'
urlpatterns = [
    path('', about_page, name='about_page')
]

Art_School_Products_Marketplace/home/urls.py
from django.urls import path , include
from .views import  home_page


app_name = 'home'
urlpatterns = [
    path('', home_page, name='home_page'),
]

Art_School_Products_Marketplace/login/urls.py
from django.urls import path
from .views import login_page, logout_page


app_name = 'login'
urlpatterns = [
    path('', login_page, name='login_page'),
    path('logout/', logout_page, name='logout_page'),
]

Art_School_Products_Marketplace/products/urls.py
from django.urls import path
from .views import products_page


app_name = 'products'
urlpatterns = [
    path('', products_page, name='products_page')
]

Art_School_Products_Marketplace/registr/urls.py
from django.urls import path
from .views import registr_page


app_name = 'registr'
urlpatterns = [
    path('', registr_page, name='registr_page')
]

Art_School_Products_Marketplace/templates/shared/header.html
{% load static %}

<header class=" flex items-center justify-between p-4 md:p-8 border-b border-grayblue w-full z-[999] duration-300 bg-white">
  <a href="{% url "home:home_page" %}"><h2 class="text-darkgray font-semibold text-xl">فروشگاه هنرستان سعدی</h2></a>
    
    <!-- Desktop Navigation -->
    <nav class="hidden md:flex text-darkgray font-medium gap-6 md:gap-10">
      <a href="{% url "about:about_page" %}" class="hover:text-dark-teal transition">داستان ما</a>
      <a href="#" class="hover:text-dark-teal transition">تماس با ما</a>
      <a href="#" class="hover:text-dark-teal transition">سوالات متداول</a>
      <a href="{% url "products:products_page" %}" class="hover:text-dark-teal transition font-semibold"> فروشگاه </a>
    </nav>
    
    {% if request.user.is_authenticated  %}
      <!-- login buttons -->
      <a href="{% url "dashboard:dashboard_page" %}" class="hidden md:block">
        <div class="bg-teal rounded-full flex justify-center items-center p-2 gap-2">
            <div class="bg-light-gray rounded-full p-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#015551" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
              </svg>        
            </div>
            <h2 class="text-light-gray text-xl font-bold px-2"> {{request.user}} </h2>
        </div>
      </a>

    {% else %}
      <!-- Desktop Buttons -->
      <div class="hidden md:flex gap-2">
        <a href="{% url "login:login_page" %}" class="px-3 md:px-4 py-2 md:py-3 text-dark-teal border-2 border-dark-teal rounded-lg hover:bg-dark-teal hover:text-white transition">ورود</a>
        <a href="{% url "registr:registr_page" %}" class="px-4 md:px-6 py-2 md:py-3 text-white bg-Orange rounded-lg hover:bg-bright-orange transition">ثبت نام</a>
      </div>
    {% endif %}

    <!-- Mobile Menu Button -->
    <button id="menubar" class="cursor-pointer md:hidden text-2xl focus:outline-none" aria-label="منو">
      <i class="fa-solid fa-bars"></i>
    </button>
  </header>
  
  <!-- Backdrop for Mobile Menu -->
  <div id="backdrop" class="fixed inset-0 w-full h-screen hidden bg-black/50 backdrop-blur-sm z-[997]"></div>
  

  <!-- Mobile Navigation Menu -->
  <div id="mobile-nav" class="md:hidden bg-dark-teal text-white flex flex-col items-center justify-center fixed w-full h-0 overflow-hidden bottom-0 duration-300 ease-in-out rounded-t-3xl left-0 z-[998]">
    <ul class="flex flex-col items-center gap-8 py-8 w-full">
      <li><a href="{% url "about:about_page" %}" class="text-xl hover:text-orange-200 transition">داستان ما</a></li>
      <li><a href="#" class="text-xl hover:text-orange-200 transition">تماس با ما</a></li>
      <li><a href="#" class="text-xl hover:text-orange-200 transition">سوالات متداول</a></li>
      <li><a href="{% url "products:products_page" %}" class="text-xl hover:text-orange-200 transition font-semibold"> فروشگاه </a></li>
    </ul>
    {% if request.user.is_authenticated  %}
      <a href="{% url "dashboard:dashboard_page" %}" class="">
        <div class="bg-Orange rounded-full flex justify-center items-center p-2 gap-2 mb-8">
            <div class="bg-light-gray rounded-full p-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#015551" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
              </svg>        
            </div>
            <h2 class="text-light-gray text-xl font-bold px-2"> {{request.user}} </h2>
        </div>
      </a>
    {% else %}
      <div class="flex gap-4 pb-8">
        <a href="{% url "login:login_page" %}" class="px-6 py-2 text-dark-teal bg-white rounded-lg hover:bg-gray-100 transition">ورود</a>
        <a href="{% url "registr:registr_page" %}" class="px-6 py-2 text-white bg-Orange rounded-lg hover:bg-bright-orange transition">ثبت نام</a>
      </div>
    {% endif %}

  </div>

Art_School_Products_Marketplace/templates/shared/main_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "home/styles/output.css" %} ">
    <link rel="stylesheet" href="{% static "home/public/fonts/fontiran.css" %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    {% block head_ref %}
    {% endblock head_ref %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body dir="rtl" >
    <!-- header section start -->
    {% include "shared/header.html" %}

    <!-- content section start -->
    {% block content %}{% endblock content %}

    {% if not hide_footer %}
        <!-- footer section start -->
        {% include "shared/footer.html" %}
    {% endif %}

   <!-- footer refrence section start -->
   {% block footer_refrence %}{% endblock footer_refrence %}
</body>

</html>