Art_School_Products_Marketplace/Art_School_Products_Marketplace/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('register/', include('registr.urls')),
    path('about/', include('about.urls')),
    path('login/', include('login.urls')),
    path('products/', include('products.urls')),
    path('products_detail/', include('products_detail.urls')),
    path('product_cards/', include('productCard.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rules/', include('rules.urls')),
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Art_School_Products_Marketplace/home/urls.py
from django.urls import path , include
from .views import  home_page


app_name = 'home'
urlpatterns = [
    path('', home_page, name='home_page'),
]

Art_School_Products_Marketplace/products/urls.py
from django.urls import path
from .views import products_page


app_name = 'products'
urlpatterns = [
    path('', products_page, name='products_page')
]

Art_School_Products_Marketplace/products_detail/urls.py
from django.urls import path
from .views import products_detail


app_name = 'products_detail'
urlpatterns = [
    path('<int:pk>', products_detail, name='products_detail'),
]

Art_School_Products_Marketplace/products/models.py
from django.db import models

class category(models.Model):
    title = models.CharField(max_length= 100, help_text="عنوان دسته بندی",null=True , blank=True )
    url_name = models.CharField(max_length=100, help_text="این عنوان برای آدرس دهی دسته بندی ها استفاده میشود, پس از این اسم حتما باید در آدرس دهی استفاده کنید.", null=True , blank=True)

    def __str__(self):
        return self.title 

class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(null=True , blank=True)
    category = models.ForeignKey(category, on_delete=models.CASCADE ,null=True , blank=True)
    is_show = models.BooleanField(default=True)

    def __str__(self):
        return self.title

Art_School_Products_Marketplace/products/views.py
from django.shortcuts import render
from django.db.models import Q
from products.models import Product, category

def products_page(request):

    search_query = request.GET.get('search')
    if search_query:
        products = Product.objects.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query),
            is_show=True
        )
        context = {
            'products': products,
            'search_query': search_query
        }
    else:
        all_products = Product.objects.filter(is_show=True)
        categories = category.objects.all()
        data = []

        for cat in categories:
            products = Product.objects.filter(category=cat, is_show=True)
            if products.exists():
                data.append({
                    'category': cat,
                    'products': products
                })

        context = {
            'categories_with_products': data,
            'products': all_products
        }
    return render(request, 'products/products.html', context)

Art_School_Products_Marketplace/products/templates/products/product_navigation.html
<nav class="w-full bg-white text-sm md:p-8 md:gap-x-2">
    <!-- نمایش در دسکتاپ -->
    <div class="hidden md:flex items-center -mt-8">
      <a href="#" class="px-4 py-8">دسته‌بندی کالا‌ها</a>
      <span class="text-grayblue">|</span>
      <a href="#digital" class="p-4">طراحی دیجیتال</a>
      <span class="text-grayblue">|</span>
      <a href="#paint" class="p-4">نقاشی و تصویرسازی</a>
      <span class="text-grayblue">|</span>
      <a href="#print" class="p-4">محصولات چاپی</a>
      <span class="text-grayblue">|</span>
      <a href="#web" class="p-4">طراحی وب سایت</a>
    </div>
    

    <!-- نمایش در موبایل -->
    <div id="mobileMenu" class="fixed inset-0 flex items-center justify-center hidden z-[999]">
        <div id="backdrop" class="absolute inset-0 bg-[#3333337D] backdrop-blur-xs z-[998] w-screen"></div>
        <div class="bg-white rounded-md max-w-md relative z-[999] container mx-auto p-2 overflow-hidden w-64">
            <h3 class="flex justify-between border-b text-base p-4 items-center font-semibold text-darkgray">
                دسته‌بندی کالاها
                <svg id="closeButton" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#45474B" class="size-4">
                    <path fill-rule="evenodd" d="M5.47 5.47a.75.75 0 0 1 1.06 0L12 10.94l5.47-5.47a.75.75 0 1 1 1.06 1.06L13.06 12l5.47 5.47a.75.75 0 1 1-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 0 1-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
                </svg>                  
            </h3>                        
            <ul class="divide-y divide-gray-200">
                <li class="p-4 cursor-pointer text-darkgray border-b font-semibold">طراحی دیجیتال</li>
                <li class="p-4 cursor-pointer text-darkgray border-b font-semibold">نقاشی و تصویرسازی</li>
                <li class="p-4 cursor-pointer text-darkgray border-b font-semibold">محصولات چاپی</li>
                <li class="p-4 cursor-pointer text-darkgray border-b font-semibold">طراحی وب‌سایت</li>
                <li class="p-4 cursor-pointer text-darkgray font-semibold">عکاسی</li>
            </ul>
    </div>
</nav>
<button id="menuButton" class="text-darkgray bg-light-gray rounded-md flex text-sm gap-2 p-2 items-center md:hidden m-4">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#45474B" class="size-6">
        <path fill-rule="evenodd" d="M3 6a3 3 0 0 1 3-3h2.25a3 3 0 0 1 3 3v2.25a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V6Zm9.75 0a3 3 0 0 1 3-3H18a3 3 0 0 1 3 3v2.25a3 3 0 0 1-3 3h-2.25a3 3 0 0 1-3-3V6ZM3 15.75a3 3 0 0 1 3-3h2.25a3 3 0 0 1 3 3V18a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3v-2.25Zm9.75 0a3 3 0 0 1 3-3H18a3 3 0 0 1 3 3V18a3 3 0 0 1-3 3h-2.25a3 3 0 0 1-3-3v-2.25Z" clip-rule="evenodd" />
    </svg>          
    دسته‌بندی کالا‌ها          
</button>

Art_School_Products_Marketplace/products/templates/products/products.html
{% extends "shared/main_layout.html" %}
{% load static %}
{% block content %}

{% include "products/product_navigation.html" %} 

<main class="flex flex-col items-center justify-center">
    {% if not search_query %}
    <section class="bg-teal flex flex-col mt-10 p-4 w-full mx-auto md:w-5/6 lg:max-w-7xl md:flex-row md:rounded-md mb-10">
        <div class="w-full md:w-1/3 flex flex-row md:flex-col md:items-center justify-between text-center py-4 px-2">
            <h3 class="text-white font-semibold text-sm sm:text-base md:text-xl">پیشنهاد <br class="hidden md:block">شگفت انگیز</h3>
            <img src="{% static 'products/public/images/01 Online Shopping 1.svg' %}" alt="پیشنهاد شگفت انگیز" class="hidden md:flex w-5/6 max-w-xs" />
            <div class="flex items-center">
                <a href="" class="text-xs sm:text-sm text-white md:text-center">مشاهده همه</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
                </svg>                  
            </div>
        </div>
        <div class="gap-2 flex mt-4 w-full overflow-x-auto sm:overflow-x-visible sm:grid sm:grid-cols-2 md:grid-cols-4">
            
            {% with all_products=products|slice:":4" %}
                {% for product in all_products %}    
                <div class="relative  bg-white rounded-xl border p-4 text-center shadow-sm flex flex-col gap-3">
                    <button class="absolute top-3 right-3 text-gray-400 cursor-pointer">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="gray" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                        </svg>
                    </button>
                    <img src="{{product.image.url}}" alt="{{ product.title }}" class="mb-3 aspect-[1/1] w-full" />
                    <h3 class="text-sm font-semibold mb-3"> {{ product.title }} </h3>
                    <p class="text-xs text-[#1E1E1E] mt-1 mb-5">{{ product.description|truncatewords:3 }}</p>        
                    <div class="flex justify-between items-center gap-6 mt-8">
                        <button class="bg-teal  rounded-lg px-4  py-2 transition text-sm text-white w-1/2"><a href="{% url "products_detail:products_detail" product.id %}">مشاهده</a></button>
                        <button class="text-teal border border-teal rounded-md  transition px-4  py-2">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                            </svg>                  
                        </button>
                    </div>
                </div>
                {% endfor %}
            {% endwith %}
        </div>
    </section>
{% endif %}

<section class="flex items-center justify-center mt-12 md:mt-20 mb-12 p-4">
    <div class="flex flex-col md:flex-row items-center justify-center gap-4 md:gap-8">
        <!-- تصویر سمت راست - فقط برای دسکتاپ -->
        <img src="{% static 'products/public/images/01 Online Shopping 3.svg' %}" 
             alt="mobile icon" 
             class="hidden md:block">
        
        <div class="text-center w-full md:w-auto">
            <h1 class="text-lg md:text-4xl lg:text-3xl font-semibold mb-4 md:mb-6">آیا دنبال محصول خاصی می‌گردی؟</h1>
            <form method="GET" action="">
                <div class="relative w-64 sm:w-80 md:w-64 lg:w-80 mx-auto flex justify-between items-center">
                    <input type="text" 
                           name="search" 
                           placeholder="جستجوی محصول" 
                           value="{{ request.GET.search }}" 
                           class="w-full px-4 py-2 rounded-lg  placeholder-[#9795B5] md:placeholder:text-base focus:outline-none focus:ring-2 bg-[#F5F5F5]" />
                    <div class="absolute top-2 left-3 text-gray-400">
                        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M12.9 14.32a8 8 0 111.414-1.414l4.387 4.387a1 1 0 01-1.414 1.414l-4.387-4.387zM8 14a6 6 0 100-12 6 6 0 000 12z" clip-rule="evenodd" />
                        </svg>
                    </div>
                </div>
            </form>
        </div>
        
        <!-- تصویر سمت چپ - فقط برای دسکتاپ -->
        <img src="{% static 'products/public/images/01 Online Shopping 2.svg' %}" 
             alt="box icon" 
             class="hidden md:block">
    </div>
</section>

    {% if search_query %}
        <h2>نتایج برای "{{ search_query }}"</h2>
        {% if products %}

            <div class="flex justify-center items-center">
                <div class="flex items-center justify-center text-white w-8 h-8 bg-dark-teal rounded-full p-2 ml-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" class="size-4  ">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>  
                </div>
                <div class="gap-2 w-11/12 flex">
                    {% for product in products %}
                    <div class="relative  bg-white rounded-xl border p-4 text-center shadow-sm flex flex-col gap-3">
                        <button class="absolute top-3 right-3 text-gray-400 cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="gray" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                            </svg>
                        </button>
                        <img src="{{ product.image.url }} " alt="محصول" class="mb-3 aspect-[1/1] w-full" />
                        <h3 class="text-sm font-semibold mb-3">{{ product.title }}</h3>
                        <p class="text-xs text-[#1E1E1E] mt-1 mb-5">{{ product.description|truncatewords:3 }}</p>        
                        <div class="flex justify-between items-center gap-6 mt-8">
                            <button class="bg-teal  rounded-lg px-4  py-2 transition text-sm text-white w-1/2"><a href="{% url "products_detail:products_detail" product.id %}">مشاهده</a></button>
                            <button class="text-teal border border-teal rounded-md  transition px-4  py-2">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                                </svg>                  
                            </button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="flex items-center justify-center text-white w-8 h-8 bg-dark-teal rounded-full p-2 mr-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
                    </svg>                  
                </div>
            </div>

        {% else %}
            <p>نتیجه‌ای یافت نشد.</p>
        {% endif %}

    {% else %}
        {% for item in categories_with_products %}

        <section class="flex flex-col justify-center items-center w-full mb-12 mt-8">
            <div class="flex justify-between items-center w-[90%] p-4 md:mb-8">
                <h1 class="font-semibold md:font-bold text-base md:text-xl">{{ item.category.title }}</h1>
                <div class="flex items-center">
                    <a href="{% url 'productCard:'|add:item.category.url_name %}" class="text-xs md:text-sm">مشاهده همه</a>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 md:w-4 md:h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
                    </svg>                  
                </div>
            </div>
        
            <div class="flex items-center justify-center px-2 md:px-8">
                <button class="hidden sm:flex items-center justify-center text-white w-6 h-6 md:w-8 md:h-8 bg-dark-teal rounded-full p-1 md:p-2 ml-1 md:ml-2 hover:bg-opacity-90 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" class="w-3 h-3 md:w-4 md:h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>  
                </button>
                
                <div class="w-full overflow-x-auto sm:overflow-hidden px-2 sm:px-4 ">
                    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-2 md:gap-4 w-max sm:w-full mx-auto">
                        {% for product in item.products %}
                            <div class="bg-white rounded-lg border p-3 text-center flex flex-col gap-2 w-[140px] xs:w-[180px] sm:w-full min-w-0">
                                <img src="{{ product.image.url }}" alt="محصول" class="mb-8 aspect-[1/1] w-full object-contain" />
                                
                                <h3 class="text-xs sm:text-base font-semibold line-clamp-1">{{ product.title }}</h3>
                                <p class="text-[10px] sm:text-xs text-[#1E1E1E] mt-1 mb-2 line-clamp-2 hidden md:block">{{ product.description|truncatewords:3 }}</p>        
                                
                                <div class="flex justify-between items-center gap-2 mt-auto w-full">
                                    <button class="bg-teal rounded-md px-2 md:py-2 py-1 text-center text-xs sm:text-sm text-white whitespace-nowrap w-full hover:bg-dark-teal transition-colors">
                                        <a href="{% url "products_detail:products_detail" product.id %}">مشاهده</a>                                    </button>
                                    <button class="text-teal border border-teal rounded-md p-1 md:p-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="md:size-5 size-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                                        </svg>                  
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                
                <button class="hidden sm:flex items-center justify-center text-white w-6 h-6 md:w-8 md:h-8 bg-dark-teal rounded-full p-1 md:p-2 mr-1 md:mr-2 hover:bg-opacity-90 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 md:w-4 md:h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
                    </svg>                  
                </button>
            </div>
        </section>
        {% endfor %}
    {% endif %}
</main>
    
{% endblock content %}
{% block footer_refrence %}
    <script src="{% static 'products/js/script.js' %}"></script>
{% endblock footer_refrence %}


{% block title %}
    محصولات
{% endblock title %}